export const GET_AUTHORIZATION = "GET_AUTHORIZATION";
export const ADD_USER = "ADD_USER";
export const GET_USER = "GET_USER";

export const GET_CONTENTS = "GET_CONTENTS";
export const GET_CONTENT = "GET_CONTENT";
export const ADD_CONTENT = "ADD_CONTENT";
export const UPDATE_CONTENT = "UPDATE_CONTENT";
export const DELETE_CONTENT = "DELETE_CONTENT";

export const GET_USER_DETAILS = "GET_USER_DETAILS";
export const ADD_USER_DETAILS = "ADD_USER_DETAILS";